#!/usr/bin/env bash

# Hook to make sure that no commit message line exceeds 72 characters

while read line; do
    if [ ${#line} -ge 72 ]; then
        echo "Commit messages are limited to 72 characters."
        echo "The following commit message has ${#line} characters."
        echo "${line}"
        exit 1
    fi
done < "${1}"

exit 0
