# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/manolee/git/raw-jit-executor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/manolee/git/raw-jit-executor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/manolee/git/raw-jit-executor/CMakeFiles /home/manolee/git/raw-jit-executor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/manolee/git/raw-jit-executor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named codegen

# Build rule for target.
codegen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 codegen
.PHONY : codegen

# fast build rule for target.
codegen/fast:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/build
.PHONY : codegen/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f CMakeFiles/gtest.dir/build.make CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named jsmn

# Build rule for target.
jsmn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jsmn
.PHONY : jsmn

# fast build rule for target.
jsmn/fast:
	$(MAKE) -f CMakeFiles/jsmn.dir/build.make CMakeFiles/jsmn.dir/build
.PHONY : jsmn/fast

#=============================================================================
# Target rules for targets named rawmain

# Build rule for target.
rawmain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rawmain
.PHONY : rawmain

# fast build rule for target.
rawmain/fast:
	$(MAKE) -f CMakeFiles/rawmain.dir/build.make CMakeFiles/rawmain.dir/build
.PHONY : rawmain/fast

#=============================================================================
# Target rules for targets named unit-tests

# Build rule for target.
unit-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit-tests
.PHONY : unit-tests

# fast build rule for target.
unit-tests/fast:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/build
.PHONY : unit-tests/fast

common/common.o: common/common.cpp.o
.PHONY : common/common.o

# target to build an object file
common/common.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/common/common.cpp.o
.PHONY : common/common.cpp.o

common/common.i: common/common.cpp.i
.PHONY : common/common.i

# target to preprocess a source file
common/common.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/common/common.cpp.i
.PHONY : common/common.cpp.i

common/common.s: common/common.cpp.s
.PHONY : common/common.s

# target to generate assembly for a file
common/common.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/common/common.cpp.s
.PHONY : common/common.cpp.s

expressions/binary-operators.o: expressions/binary-operators.cpp.o
.PHONY : expressions/binary-operators.o

# target to build an object file
expressions/binary-operators.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/binary-operators.cpp.o
.PHONY : expressions/binary-operators.cpp.o

expressions/binary-operators.i: expressions/binary-operators.cpp.i
.PHONY : expressions/binary-operators.i

# target to preprocess a source file
expressions/binary-operators.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/binary-operators.cpp.i
.PHONY : expressions/binary-operators.cpp.i

expressions/binary-operators.s: expressions/binary-operators.cpp.s
.PHONY : expressions/binary-operators.s

# target to generate assembly for a file
expressions/binary-operators.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/binary-operators.cpp.s
.PHONY : expressions/binary-operators.cpp.s

expressions/expressions-flusher.o: expressions/expressions-flusher.cpp.o
.PHONY : expressions/expressions-flusher.o

# target to build an object file
expressions/expressions-flusher.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/expressions-flusher.cpp.o
.PHONY : expressions/expressions-flusher.cpp.o

expressions/expressions-flusher.i: expressions/expressions-flusher.cpp.i
.PHONY : expressions/expressions-flusher.i

# target to preprocess a source file
expressions/expressions-flusher.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/expressions-flusher.cpp.i
.PHONY : expressions/expressions-flusher.cpp.i

expressions/expressions-flusher.s: expressions/expressions-flusher.cpp.s
.PHONY : expressions/expressions-flusher.s

# target to generate assembly for a file
expressions/expressions-flusher.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/expressions-flusher.cpp.s
.PHONY : expressions/expressions-flusher.cpp.s

expressions/expressions-generator.o: expressions/expressions-generator.cpp.o
.PHONY : expressions/expressions-generator.o

# target to build an object file
expressions/expressions-generator.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/expressions-generator.cpp.o
.PHONY : expressions/expressions-generator.cpp.o

expressions/expressions-generator.i: expressions/expressions-generator.cpp.i
.PHONY : expressions/expressions-generator.i

# target to preprocess a source file
expressions/expressions-generator.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/expressions-generator.cpp.i
.PHONY : expressions/expressions-generator.cpp.i

expressions/expressions-generator.s: expressions/expressions-generator.cpp.s
.PHONY : expressions/expressions-generator.s

# target to generate assembly for a file
expressions/expressions-generator.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/expressions-generator.cpp.s
.PHONY : expressions/expressions-generator.cpp.s

expressions/expressions-hasher.o: expressions/expressions-hasher.cpp.o
.PHONY : expressions/expressions-hasher.o

# target to build an object file
expressions/expressions-hasher.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/expressions-hasher.cpp.o
.PHONY : expressions/expressions-hasher.cpp.o

expressions/expressions-hasher.i: expressions/expressions-hasher.cpp.i
.PHONY : expressions/expressions-hasher.i

# target to preprocess a source file
expressions/expressions-hasher.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/expressions-hasher.cpp.i
.PHONY : expressions/expressions-hasher.cpp.i

expressions/expressions-hasher.s: expressions/expressions-hasher.cpp.s
.PHONY : expressions/expressions-hasher.s

# target to generate assembly for a file
expressions/expressions-hasher.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/expressions-hasher.cpp.s
.PHONY : expressions/expressions-hasher.cpp.s

expressions/expressions.o: expressions/expressions.cpp.o
.PHONY : expressions/expressions.o

# target to build an object file
expressions/expressions.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/expressions.cpp.o
.PHONY : expressions/expressions.cpp.o

expressions/expressions.i: expressions/expressions.cpp.i
.PHONY : expressions/expressions.i

# target to preprocess a source file
expressions/expressions.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/expressions.cpp.i
.PHONY : expressions/expressions.cpp.i

expressions/expressions.s: expressions/expressions.cpp.s
.PHONY : expressions/expressions.s

# target to generate assembly for a file
expressions/expressions.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/expressions.cpp.s
.PHONY : expressions/expressions.cpp.s

expressions/path.o: expressions/path.cpp.o
.PHONY : expressions/path.o

# target to build an object file
expressions/path.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/path.cpp.o
.PHONY : expressions/path.cpp.o

expressions/path.i: expressions/path.cpp.i
.PHONY : expressions/path.i

# target to preprocess a source file
expressions/path.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/path.cpp.i
.PHONY : expressions/path.cpp.i

expressions/path.s: expressions/path.cpp.s
.PHONY : expressions/path.s

# target to generate assembly for a file
expressions/path.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/expressions/path.cpp.s
.PHONY : expressions/path.cpp.s

jsmn/jsmn.o: jsmn/jsmn.c.o
.PHONY : jsmn/jsmn.o

# target to build an object file
jsmn/jsmn.c.o:
	$(MAKE) -f CMakeFiles/jsmn.dir/build.make CMakeFiles/jsmn.dir/jsmn/jsmn.c.o
.PHONY : jsmn/jsmn.c.o

jsmn/jsmn.i: jsmn/jsmn.c.i
.PHONY : jsmn/jsmn.i

# target to preprocess a source file
jsmn/jsmn.c.i:
	$(MAKE) -f CMakeFiles/jsmn.dir/build.make CMakeFiles/jsmn.dir/jsmn/jsmn.c.i
.PHONY : jsmn/jsmn.c.i

jsmn/jsmn.s: jsmn/jsmn.c.s
.PHONY : jsmn/jsmn.s

# target to generate assembly for a file
jsmn/jsmn.c.s:
	$(MAKE) -f CMakeFiles/jsmn.dir/build.make CMakeFiles/jsmn.dir/jsmn/jsmn.c.s
.PHONY : jsmn/jsmn.c.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/rawmain.dir/build.make CMakeFiles/rawmain.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/rawmain.dir/build.make CMakeFiles/rawmain.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/rawmain.dir/build.make CMakeFiles/rawmain.dir/main.cpp.s
.PHONY : main.cpp.s

memory/memory-allocator.o: memory/memory-allocator.cpp.o
.PHONY : memory/memory-allocator.o

# target to build an object file
memory/memory-allocator.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/memory/memory-allocator.cpp.o
.PHONY : memory/memory-allocator.cpp.o

memory/memory-allocator.i: memory/memory-allocator.cpp.i
.PHONY : memory/memory-allocator.i

# target to preprocess a source file
memory/memory-allocator.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/memory/memory-allocator.cpp.i
.PHONY : memory/memory-allocator.cpp.i

memory/memory-allocator.s: memory/memory-allocator.cpp.s
.PHONY : memory/memory-allocator.s

# target to generate assembly for a file
memory/memory-allocator.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/memory/memory-allocator.cpp.s
.PHONY : memory/memory-allocator.cpp.s

operators/join.o: operators/join.cpp.o
.PHONY : operators/join.o

# target to build an object file
operators/join.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/join.cpp.o
.PHONY : operators/join.cpp.o

operators/join.i: operators/join.cpp.i
.PHONY : operators/join.i

# target to preprocess a source file
operators/join.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/join.cpp.i
.PHONY : operators/join.cpp.i

operators/join.s: operators/join.cpp.s
.PHONY : operators/join.s

# target to generate assembly for a file
operators/join.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/join.cpp.s
.PHONY : operators/join.cpp.s

operators/nest.o: operators/nest.cpp.o
.PHONY : operators/nest.o

# target to build an object file
operators/nest.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/nest.cpp.o
.PHONY : operators/nest.cpp.o

operators/nest.i: operators/nest.cpp.i
.PHONY : operators/nest.i

# target to preprocess a source file
operators/nest.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/nest.cpp.i
.PHONY : operators/nest.cpp.i

operators/nest.s: operators/nest.cpp.s
.PHONY : operators/nest.s

# target to generate assembly for a file
operators/nest.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/nest.cpp.s
.PHONY : operators/nest.cpp.s

operators/outer-unnest.o: operators/outer-unnest.cpp.o
.PHONY : operators/outer-unnest.o

# target to build an object file
operators/outer-unnest.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/outer-unnest.cpp.o
.PHONY : operators/outer-unnest.cpp.o

operators/outer-unnest.i: operators/outer-unnest.cpp.i
.PHONY : operators/outer-unnest.i

# target to preprocess a source file
operators/outer-unnest.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/outer-unnest.cpp.i
.PHONY : operators/outer-unnest.cpp.i

operators/outer-unnest.s: operators/outer-unnest.cpp.s
.PHONY : operators/outer-unnest.s

# target to generate assembly for a file
operators/outer-unnest.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/outer-unnest.cpp.s
.PHONY : operators/outer-unnest.cpp.s

operators/print.o: operators/print.cpp.o
.PHONY : operators/print.o

# target to build an object file
operators/print.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/print.cpp.o
.PHONY : operators/print.cpp.o

operators/print.i: operators/print.cpp.i
.PHONY : operators/print.i

# target to preprocess a source file
operators/print.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/print.cpp.i
.PHONY : operators/print.cpp.i

operators/print.s: operators/print.cpp.s
.PHONY : operators/print.s

# target to generate assembly for a file
operators/print.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/print.cpp.s
.PHONY : operators/print.cpp.s

operators/radix-join.o: operators/radix-join.cpp.o
.PHONY : operators/radix-join.o

# target to build an object file
operators/radix-join.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/radix-join.cpp.o
.PHONY : operators/radix-join.cpp.o

operators/radix-join.i: operators/radix-join.cpp.i
.PHONY : operators/radix-join.i

# target to preprocess a source file
operators/radix-join.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/radix-join.cpp.i
.PHONY : operators/radix-join.cpp.i

operators/radix-join.s: operators/radix-join.cpp.s
.PHONY : operators/radix-join.s

# target to generate assembly for a file
operators/radix-join.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/radix-join.cpp.s
.PHONY : operators/radix-join.cpp.s

operators/reduce.o: operators/reduce.cpp.o
.PHONY : operators/reduce.o

# target to build an object file
operators/reduce.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/reduce.cpp.o
.PHONY : operators/reduce.cpp.o

operators/reduce.i: operators/reduce.cpp.i
.PHONY : operators/reduce.i

# target to preprocess a source file
operators/reduce.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/reduce.cpp.i
.PHONY : operators/reduce.cpp.i

operators/reduce.s: operators/reduce.cpp.s
.PHONY : operators/reduce.s

# target to generate assembly for a file
operators/reduce.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/reduce.cpp.s
.PHONY : operators/reduce.cpp.s

operators/root.o: operators/root.cpp.o
.PHONY : operators/root.o

# target to build an object file
operators/root.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/root.cpp.o
.PHONY : operators/root.cpp.o

operators/root.i: operators/root.cpp.i
.PHONY : operators/root.i

# target to preprocess a source file
operators/root.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/root.cpp.i
.PHONY : operators/root.cpp.i

operators/root.s: operators/root.cpp.s
.PHONY : operators/root.s

# target to generate assembly for a file
operators/root.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/root.cpp.s
.PHONY : operators/root.cpp.s

operators/scan.o: operators/scan.cpp.o
.PHONY : operators/scan.o

# target to build an object file
operators/scan.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/scan.cpp.o
.PHONY : operators/scan.cpp.o

operators/scan.i: operators/scan.cpp.i
.PHONY : operators/scan.i

# target to preprocess a source file
operators/scan.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/scan.cpp.i
.PHONY : operators/scan.cpp.i

operators/scan.s: operators/scan.cpp.s
.PHONY : operators/scan.s

# target to generate assembly for a file
operators/scan.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/scan.cpp.s
.PHONY : operators/scan.cpp.s

operators/select.o: operators/select.cpp.o
.PHONY : operators/select.o

# target to build an object file
operators/select.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/select.cpp.o
.PHONY : operators/select.cpp.o

operators/select.i: operators/select.cpp.i
.PHONY : operators/select.i

# target to preprocess a source file
operators/select.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/select.cpp.i
.PHONY : operators/select.cpp.i

operators/select.s: operators/select.cpp.s
.PHONY : operators/select.s

# target to generate assembly for a file
operators/select.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/select.cpp.s
.PHONY : operators/select.cpp.s

operators/unnest.o: operators/unnest.cpp.o
.PHONY : operators/unnest.o

# target to build an object file
operators/unnest.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/unnest.cpp.o
.PHONY : operators/unnest.cpp.o

operators/unnest.i: operators/unnest.cpp.i
.PHONY : operators/unnest.i

# target to preprocess a source file
operators/unnest.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/unnest.cpp.i
.PHONY : operators/unnest.cpp.i

operators/unnest.s: operators/unnest.cpp.s
.PHONY : operators/unnest.s

# target to generate assembly for a file
operators/unnest.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/operators/unnest.cpp.s
.PHONY : operators/unnest.cpp.s

plugins/binary-col-plugin.o: plugins/binary-col-plugin.cpp.o
.PHONY : plugins/binary-col-plugin.o

# target to build an object file
plugins/binary-col-plugin.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/binary-col-plugin.cpp.o
.PHONY : plugins/binary-col-plugin.cpp.o

plugins/binary-col-plugin.i: plugins/binary-col-plugin.cpp.i
.PHONY : plugins/binary-col-plugin.i

# target to preprocess a source file
plugins/binary-col-plugin.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/binary-col-plugin.cpp.i
.PHONY : plugins/binary-col-plugin.cpp.i

plugins/binary-col-plugin.s: plugins/binary-col-plugin.cpp.s
.PHONY : plugins/binary-col-plugin.s

# target to generate assembly for a file
plugins/binary-col-plugin.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/binary-col-plugin.cpp.s
.PHONY : plugins/binary-col-plugin.cpp.s

plugins/binary-row-plugin.o: plugins/binary-row-plugin.cpp.o
.PHONY : plugins/binary-row-plugin.o

# target to build an object file
plugins/binary-row-plugin.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/binary-row-plugin.cpp.o
.PHONY : plugins/binary-row-plugin.cpp.o

plugins/binary-row-plugin.i: plugins/binary-row-plugin.cpp.i
.PHONY : plugins/binary-row-plugin.i

# target to preprocess a source file
plugins/binary-row-plugin.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/binary-row-plugin.cpp.i
.PHONY : plugins/binary-row-plugin.cpp.i

plugins/binary-row-plugin.s: plugins/binary-row-plugin.cpp.s
.PHONY : plugins/binary-row-plugin.s

# target to generate assembly for a file
plugins/binary-row-plugin.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/binary-row-plugin.cpp.s
.PHONY : plugins/binary-row-plugin.cpp.s

plugins/csv-plugin.o: plugins/csv-plugin.cpp.o
.PHONY : plugins/csv-plugin.o

# target to build an object file
plugins/csv-plugin.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/csv-plugin.cpp.o
.PHONY : plugins/csv-plugin.cpp.o

plugins/csv-plugin.i: plugins/csv-plugin.cpp.i
.PHONY : plugins/csv-plugin.i

# target to preprocess a source file
plugins/csv-plugin.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/csv-plugin.cpp.i
.PHONY : plugins/csv-plugin.cpp.i

plugins/csv-plugin.s: plugins/csv-plugin.cpp.s
.PHONY : plugins/csv-plugin.s

# target to generate assembly for a file
plugins/csv-plugin.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/csv-plugin.cpp.s
.PHONY : plugins/csv-plugin.cpp.s

plugins/json-jsmn-plugin.o: plugins/json-jsmn-plugin.cpp.o
.PHONY : plugins/json-jsmn-plugin.o

# target to build an object file
plugins/json-jsmn-plugin.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/json-jsmn-plugin.cpp.o
.PHONY : plugins/json-jsmn-plugin.cpp.o

plugins/json-jsmn-plugin.i: plugins/json-jsmn-plugin.cpp.i
.PHONY : plugins/json-jsmn-plugin.i

# target to preprocess a source file
plugins/json-jsmn-plugin.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/json-jsmn-plugin.cpp.i
.PHONY : plugins/json-jsmn-plugin.cpp.i

plugins/json-jsmn-plugin.s: plugins/json-jsmn-plugin.cpp.s
.PHONY : plugins/json-jsmn-plugin.s

# target to generate assembly for a file
plugins/json-jsmn-plugin.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/json-jsmn-plugin.cpp.s
.PHONY : plugins/json-jsmn-plugin.cpp.s

plugins/output/plugins-output.o: plugins/output/plugins-output.cpp.o
.PHONY : plugins/output/plugins-output.o

# target to build an object file
plugins/output/plugins-output.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/output/plugins-output.cpp.o
.PHONY : plugins/output/plugins-output.cpp.o

plugins/output/plugins-output.i: plugins/output/plugins-output.cpp.i
.PHONY : plugins/output/plugins-output.i

# target to preprocess a source file
plugins/output/plugins-output.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/output/plugins-output.cpp.i
.PHONY : plugins/output/plugins-output.cpp.i

plugins/output/plugins-output.s: plugins/output/plugins-output.cpp.s
.PHONY : plugins/output/plugins-output.s

# target to generate assembly for a file
plugins/output/plugins-output.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/plugins/output/plugins-output.cpp.s
.PHONY : plugins/output/plugins-output.cpp.s

tests/tests-hashing.o: tests/tests-hashing.cpp.o
.PHONY : tests/tests-hashing.o

# target to build an object file
tests/tests-hashing.cpp.o:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/tests/tests-hashing.cpp.o
.PHONY : tests/tests-hashing.cpp.o

tests/tests-hashing.i: tests/tests-hashing.cpp.i
.PHONY : tests/tests-hashing.i

# target to preprocess a source file
tests/tests-hashing.cpp.i:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/tests/tests-hashing.cpp.i
.PHONY : tests/tests-hashing.cpp.i

tests/tests-hashing.s: tests/tests-hashing.cpp.s
.PHONY : tests/tests-hashing.s

# target to generate assembly for a file
tests/tests-hashing.cpp.s:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/tests/tests-hashing.cpp.s
.PHONY : tests/tests-hashing.cpp.s

tests/tests-operators.o: tests/tests-operators.cpp.o
.PHONY : tests/tests-operators.o

# target to build an object file
tests/tests-operators.cpp.o:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/tests/tests-operators.cpp.o
.PHONY : tests/tests-operators.cpp.o

tests/tests-operators.i: tests/tests-operators.cpp.i
.PHONY : tests/tests-operators.i

# target to preprocess a source file
tests/tests-operators.cpp.i:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/tests/tests-operators.cpp.i
.PHONY : tests/tests-operators.cpp.i

tests/tests-operators.s: tests/tests-operators.cpp.s
.PHONY : tests/tests-operators.s

# target to generate assembly for a file
tests/tests-operators.cpp.s:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/tests/tests-operators.cpp.s
.PHONY : tests/tests-operators.cpp.s

tests/tests-sailors.o: tests/tests-sailors.cpp.o
.PHONY : tests/tests-sailors.o

# target to build an object file
tests/tests-sailors.cpp.o:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/tests/tests-sailors.cpp.o
.PHONY : tests/tests-sailors.cpp.o

tests/tests-sailors.i: tests/tests-sailors.cpp.i
.PHONY : tests/tests-sailors.i

# target to preprocess a source file
tests/tests-sailors.cpp.i:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/tests/tests-sailors.cpp.i
.PHONY : tests/tests-sailors.cpp.i

tests/tests-sailors.s: tests/tests-sailors.cpp.s
.PHONY : tests/tests-sailors.s

# target to generate assembly for a file
tests/tests-sailors.cpp.s:
	$(MAKE) -f CMakeFiles/unit-tests.dir/build.make CMakeFiles/unit-tests.dir/tests/tests-sailors.cpp.s
.PHONY : tests/tests-sailors.cpp.s

util/joins/radix-join.o: util/joins/radix-join.cpp.o
.PHONY : util/joins/radix-join.o

# target to build an object file
util/joins/radix-join.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/util/joins/radix-join.cpp.o
.PHONY : util/joins/radix-join.cpp.o

util/joins/radix-join.i: util/joins/radix-join.cpp.i
.PHONY : util/joins/radix-join.i

# target to preprocess a source file
util/joins/radix-join.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/util/joins/radix-join.cpp.i
.PHONY : util/joins/radix-join.cpp.i

util/joins/radix-join.s: util/joins/radix-join.cpp.s
.PHONY : util/joins/radix-join.s

# target to generate assembly for a file
util/joins/radix-join.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/util/joins/radix-join.cpp.s
.PHONY : util/joins/radix-join.cpp.s

util/raw-catalog.o: util/raw-catalog.cpp.o
.PHONY : util/raw-catalog.o

# target to build an object file
util/raw-catalog.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/util/raw-catalog.cpp.o
.PHONY : util/raw-catalog.cpp.o

util/raw-catalog.i: util/raw-catalog.cpp.i
.PHONY : util/raw-catalog.i

# target to preprocess a source file
util/raw-catalog.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/util/raw-catalog.cpp.i
.PHONY : util/raw-catalog.cpp.i

util/raw-catalog.s: util/raw-catalog.cpp.s
.PHONY : util/raw-catalog.s

# target to generate assembly for a file
util/raw-catalog.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/util/raw-catalog.cpp.s
.PHONY : util/raw-catalog.cpp.s

util/raw-context.o: util/raw-context.cpp.o
.PHONY : util/raw-context.o

# target to build an object file
util/raw-context.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/util/raw-context.cpp.o
.PHONY : util/raw-context.cpp.o

util/raw-context.i: util/raw-context.cpp.i
.PHONY : util/raw-context.i

# target to preprocess a source file
util/raw-context.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/util/raw-context.cpp.i
.PHONY : util/raw-context.cpp.i

util/raw-context.s: util/raw-context.cpp.s
.PHONY : util/raw-context.s

# target to generate assembly for a file
util/raw-context.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/util/raw-context.cpp.s
.PHONY : util/raw-context.cpp.s

values/expressionTypes.o: values/expressionTypes.cpp.o
.PHONY : values/expressionTypes.o

# target to build an object file
values/expressionTypes.cpp.o:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/values/expressionTypes.cpp.o
.PHONY : values/expressionTypes.cpp.o

values/expressionTypes.i: values/expressionTypes.cpp.i
.PHONY : values/expressionTypes.i

# target to preprocess a source file
values/expressionTypes.cpp.i:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/values/expressionTypes.cpp.i
.PHONY : values/expressionTypes.cpp.i

values/expressionTypes.s: values/expressionTypes.cpp.s
.PHONY : values/expressionTypes.s

# target to generate assembly for a file
values/expressionTypes.cpp.s:
	$(MAKE) -f CMakeFiles/codegen.dir/build.make CMakeFiles/codegen.dir/values/expressionTypes.cpp.s
.PHONY : values/expressionTypes.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... gtest"
	@echo "... jsmn"
	@echo "... rawmain"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... unit-tests"
	@echo "... common/common.o"
	@echo "... common/common.i"
	@echo "... common/common.s"
	@echo "... expressions/binary-operators.o"
	@echo "... expressions/binary-operators.i"
	@echo "... expressions/binary-operators.s"
	@echo "... expressions/expressions-flusher.o"
	@echo "... expressions/expressions-flusher.i"
	@echo "... expressions/expressions-flusher.s"
	@echo "... expressions/expressions-generator.o"
	@echo "... expressions/expressions-generator.i"
	@echo "... expressions/expressions-generator.s"
	@echo "... expressions/expressions-hasher.o"
	@echo "... expressions/expressions-hasher.i"
	@echo "... expressions/expressions-hasher.s"
	@echo "... expressions/expressions.o"
	@echo "... expressions/expressions.i"
	@echo "... expressions/expressions.s"
	@echo "... expressions/path.o"
	@echo "... expressions/path.i"
	@echo "... expressions/path.s"
	@echo "... jsmn/jsmn.o"
	@echo "... jsmn/jsmn.i"
	@echo "... jsmn/jsmn.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... memory/memory-allocator.o"
	@echo "... memory/memory-allocator.i"
	@echo "... memory/memory-allocator.s"
	@echo "... operators/join.o"
	@echo "... operators/join.i"
	@echo "... operators/join.s"
	@echo "... operators/nest.o"
	@echo "... operators/nest.i"
	@echo "... operators/nest.s"
	@echo "... operators/outer-unnest.o"
	@echo "... operators/outer-unnest.i"
	@echo "... operators/outer-unnest.s"
	@echo "... operators/print.o"
	@echo "... operators/print.i"
	@echo "... operators/print.s"
	@echo "... operators/radix-join.o"
	@echo "... operators/radix-join.i"
	@echo "... operators/radix-join.s"
	@echo "... operators/reduce.o"
	@echo "... operators/reduce.i"
	@echo "... operators/reduce.s"
	@echo "... operators/root.o"
	@echo "... operators/root.i"
	@echo "... operators/root.s"
	@echo "... operators/scan.o"
	@echo "... operators/scan.i"
	@echo "... operators/scan.s"
	@echo "... operators/select.o"
	@echo "... operators/select.i"
	@echo "... operators/select.s"
	@echo "... operators/unnest.o"
	@echo "... operators/unnest.i"
	@echo "... operators/unnest.s"
	@echo "... plugins/binary-col-plugin.o"
	@echo "... plugins/binary-col-plugin.i"
	@echo "... plugins/binary-col-plugin.s"
	@echo "... plugins/binary-row-plugin.o"
	@echo "... plugins/binary-row-plugin.i"
	@echo "... plugins/binary-row-plugin.s"
	@echo "... plugins/csv-plugin.o"
	@echo "... plugins/csv-plugin.i"
	@echo "... plugins/csv-plugin.s"
	@echo "... plugins/json-jsmn-plugin.o"
	@echo "... plugins/json-jsmn-plugin.i"
	@echo "... plugins/json-jsmn-plugin.s"
	@echo "... plugins/output/plugins-output.o"
	@echo "... plugins/output/plugins-output.i"
	@echo "... plugins/output/plugins-output.s"
	@echo "... tests/tests-hashing.o"
	@echo "... tests/tests-hashing.i"
	@echo "... tests/tests-hashing.s"
	@echo "... tests/tests-operators.o"
	@echo "... tests/tests-operators.i"
	@echo "... tests/tests-operators.s"
	@echo "... tests/tests-sailors.o"
	@echo "... tests/tests-sailors.i"
	@echo "... tests/tests-sailors.s"
	@echo "... util/joins/radix-join.o"
	@echo "... util/joins/radix-join.i"
	@echo "... util/joins/radix-join.s"
	@echo "... util/raw-catalog.o"
	@echo "... util/raw-catalog.i"
	@echo "... util/raw-catalog.s"
	@echo "... util/raw-context.o"
	@echo "... util/raw-context.i"
	@echo "... util/raw-context.s"
	@echo "... values/expressionTypes.o"
	@echo "... values/expressionTypes.i"
	@echo "... values/expressionTypes.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

