/*
    Proteus -- High-performance query processing on heterogeneous hardware.

                            Copyright (c) 2019
        Data Intensive Applications and Systems Laboratory (DIAS)
                École Polytechnique Fédérale de Lausanne

                            All Rights Reserved.

    Permission to use, copy, modify and distribute this software and
    its documentation is hereby granted, provided that both the
    copyright notice and this permission notice appear in all copies of
    the software, derivative works or modified versions, and any
    portions thereof, and that both notices appear in supporting
    documentation.

    This code is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. THE AUTHORS
    DISCLAIM ANY LIABILITY OF ANY KIND FOR ANY DAMAGES WHATSOEVER
    RESULTING FROM THE USE OF THIS SOFTWARE.
*/

// AUTOGENERATED FILE. DO NOT EDIT.

constexpr auto query = "ssb100_Q3_3";

#include "query.cpp.inc"

PreparedStatement Query::prepare33(bool memmv, size_t bloomSize) {
  auto rel39560 =
      getBuilder<Tplugin>()
          .scan<Tplugin>(
              "inputs/ssbm100/date.csv", {"d_datekey", "d_year"},
              getCatalog())  // (table=[[SSB, ssbm_date]], fields=[[0, 4]],
                             // traits=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .membrdcst(dop, true, true)
          .router(
              [&](const auto &arg) -> std::optional<expression_t> {
                return arg["__broadcastTarget"];
              },
              dop, 1, RoutingPolicy::HASH_BASED, dev,
              aff_parallel())  // (trait=[Pelago.[].packed.X86_64.homBrdcst.hetSingle])
          .to_gpu()  // (trait=[Pelago.[].packed.NVPTX.homBrdcst.hetSingle])
          .unpack()  // (trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle])
          .filter([&](const auto &arg) -> expression_t {
            return (ge(arg["d_year"], 1992) & le(arg["d_year"], 1997));
          })  // (condition=[AND(>=($1, 1992), <=($1, 1997))],
              // trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle],
              // isS=[false])
      ;
  auto rel39564 =
      getBuilder<Tplugin>()
          .scan<Tplugin>(
              "inputs/ssbm100/customer.csv", {"c_custkey", "c_city"},
              getCatalog())  // (table=[[SSB, ssbm_customer]], fields=[[0, 3]],
                             // traits=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .membrdcst(dop, true, true)
          .router(
              [&](const auto &arg) -> std::optional<expression_t> {
                return arg["__broadcastTarget"];
              },
              dop, 1, RoutingPolicy::HASH_BASED, dev,
              aff_parallel())  // (trait=[Pelago.[].packed.X86_64.homBrdcst.hetSingle])
          .to_gpu()  // (trait=[Pelago.[].packed.NVPTX.homBrdcst.hetSingle])
          .unpack()  // (trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle])
          .filter([&](const auto &arg) -> expression_t {
            return (eq(arg["c_city"], "UNITED KI1") |
                    eq(arg["c_city"], "UNITED KI5"));
          })  // (condition=[OR(=($1, 'UNITED KI1'), =($1, 'UNITED KI5'))],
              // trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle],
              // isS=[false])
      ;
  auto rel39568 =
      getBuilder<Tplugin>()
          .scan<Tplugin>(
              "inputs/ssbm100/supplier.csv", {"s_suppkey", "s_city"},
              getCatalog())  // (table=[[SSB, ssbm_supplier]], fields=[[0, 3]],
                             // traits=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .membrdcst(dop, true, true)
          .router(
              [&](const auto &arg) -> std::optional<expression_t> {
                return arg["__broadcastTarget"];
              },
              dop, 128, RoutingPolicy::HASH_BASED, dev,
              aff_parallel())  // (trait=[Pelago.[].packed.X86_64.homBrdcst.hetSingle])
          .unpack()  // (trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle])
          .filter([&](const auto &arg) -> expression_t {
            return (eq(arg["s_city"], "UNITED KI1") |
                    eq(arg["s_city"], "UNITED KI5"));
          })
          .bloomfilter_build(
              [&](const auto &arg) -> expression_t { return arg["s_suppkey"]; },
              bloomSize, 1)
          .pack()
          .to_gpu()
          .unpack();
  auto rel =
      getBuilder<Tplugin>()
          .scan("inputs/ssbm100/lineorder.csv",
                {"lo_custkey", "lo_suppkey", "lo_orderdate", "lo_revenue"},
                getCatalog(), pg{"block"})
          .router(8, RoutingPolicy::LOCAL, DeviceType::CPU)
          //          .unpack()
          .bloomfilter_repack(
              [&](const auto &arg) { return arg["lo_suppkey"]; }, bloomSize, 1)
          //          .pack()
          .router(8, RoutingPolicy::LOCAL, dev);

  if (memmv) rel = rel.memmove(8, dev);

  rel =
      rel.to_gpu()   // (trait=[Pelago.[].packed.NVPTX.homRandom.hetSingle])
          .unpack()  // (trait=[Pelago.[].unpckd.NVPTX.homRandom.hetSingle])
          .join(
              rel39564,
              [&](const auto &build_arg) -> expression_t {
                return build_arg["$0"];
              },
              [&](const auto &probe_arg) -> expression_t {
                return probe_arg["lo_custkey"];
              },
              16,
              32768)  // (condition=[=($2, $0)], joinType=[inner],
                      // rowcnt=[2.4576E7], maxrow=[3000000.0],
                      // maxEst=[3000000.0], h_bits=[27],
                      // build=[RecordType(INTEGER c_custkey, VARCHAR
                      // c_city)], lcount=[8.70502961749499E8],
                      // rcount=[2.45775624192E9], buildcountrow=[2.4576E7],
                      // probecountrow=[2.45775624192E9])
          .join(
              rel39568,
              [&](const auto &build_arg) -> expression_t {
                return build_arg["$0"];
              },
              [&](const auto &probe_arg) -> expression_t {
                return probe_arg["lo_suppkey"];
              },
              13,
              2048)  // (condition=[=($3, $0)], joinType=[inner],
                     // rowcnt=[1638400.0], maxrow=[200000.0],
                     // maxEst=[200000.0], h_bits=[23],
                     // build=[RecordType(INTEGER s_suppkey, VARCHAR s_city)],
                     // lcount=[4.915979188432821E7],
                     // rcount=[3.0721953024E11], buildcountrow=[1638400.0],
                     // probecountrow=[3.0721953024E11])
          .join(
              rel39560,
              [&](const auto &build_arg) -> expression_t {
                return build_arg["$0"];
              },
              [&](const auto &probe_arg) -> expression_t {
                return probe_arg["lo_orderdate"];
              },
              14,
              2556)  // (condition=[=($2, $0)], joinType=[inner],
                     // rowcnt=[654336.0], maxrow=[2556.0], maxEst=[2556.0],
                     // h_bits=[22], build=[RecordType(INTEGER d_datekey,
                     // INTEGER d_year)], lcount=[1.8432021459974352E7],
                     // rcount=[1.966204993536E7], buildcountrow=[654336.0],
                     // probecountrow=[1.966204993536E7])
          .groupby(
              [&](const auto &arg) -> std::vector<expression_t> {
                return {arg["c_city"].as("PelagoAggregate#39578", "c_city"),
                        arg["s_city"].as("PelagoAggregate#39578", "s_city"),
                        arg["d_year"].as("PelagoAggregate#39578", "d_year")};
              },
              [&](const auto &arg) -> std::vector<GpuAggrMatExpr> {
                return {GpuAggrMatExpr{
                    (arg["lo_revenue"])
                        .as("PelagoAggregate#39578", "lo_revenue"),
                    1, 0, SUM}};
              },
              10,
              131072)  // (group=[{0, 1, 2}], lo_revenue=[SUM($3)],
                       // trait=[Pelago.[].unpckd.NVPTX.homRandom.hetSingle])
          .pack()      // (trait=[Pelago.[].packed.NVPTX.homRandom.hetSingle],
                       // intrait=[Pelago.[].unpckd.NVPTX.homRandom.hetSingle],
          // inputRows=[491551.248384], cost=[{1.6016 rows, 1.6 cpu, 0.0
          // io}])
          .to_cpu()  // (trait=[Pelago.[].packed.X86_64.homRandom.hetSingle])
          .router(
              DegreeOfParallelism{1}, 128, RoutingPolicy::RANDOM,
              DeviceType::CPU,
              aff_reduce())  // (trait=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .memmove(8, DeviceType::CPU)
          .unpack()  // (trait=[Pelago.[].unpckd.NVPTX.homSingle.hetSingle])
          .groupby(
              [&](const auto &arg) -> std::vector<expression_t> {
                return {arg["c_city"].as("PelagoAggregate#39584", "c_city"),
                        arg["s_city"].as("PelagoAggregate#39584", "s_city"),
                        arg["d_year"].as("PelagoAggregate#39584", "d_year")};
              },
              [&](const auto &arg) -> std::vector<GpuAggrMatExpr> {
                return {GpuAggrMatExpr{
                    (arg["lo_revenue"])
                        .as("PelagoAggregate#39584", "lo_revenue"),
                    1, 0, SUM}};
              },
              10,
              131072)  // (group=[{0, 1, 2}], lo_revenue=[SUM($3)],
                       // trait=[Pelago.[].unpckd.NVPTX.homSingle.hetSingle])
          .sort(
              [&](const auto &arg) -> std::vector<expression_t> {
                return {arg["c_city"], arg["s_city"], arg["d_year"],
                        arg["lo_revenue"]};
              },
              {direction::NONE, direction::NONE, direction::ASC,
               direction::DESC})
          // (sort0=[$2], sort1=[$3], dir0=[ASC],
          // dir1=[DESC], trait=[Pelago.[2, 3
          // DESC].unpckd.X86_64.homSingle.hetSingle])
          .print(pg{"pm-csv"})  // (trait=[ENUMERABLE.[2, 3
                                // DESC].unpckd.X86_64.homSingle.hetSingle])
      ;
  return rel.prepare();
}

PreparedStatement Query::prepare33_b(bool memmv, size_t bloomSize) {
  auto rel =
      getBuilder<Tplugin>()
          .scan("inputs/ssbm100/lineorder.csv",
                {"lo_custkey", "lo_suppkey", "lo_orderdate", "lo_revenue"},
                getCatalog(), pg{"block"})
          .router(8, RoutingPolicy::LOCAL, DeviceType::CPU)
          .unpack()
          .bloomfilter_probe([&](const auto &arg) { return arg["lo_suppkey"]; },
                             bloomSize, 1)
          .reduce(
              [&](const auto &arg) -> std::vector<expression_t> {
                return {expression_t{int64_t{1}}.as("tmp", "cnt")};
              },
              {SUM})
          .router(
              DegreeOfParallelism{1}, 128, RoutingPolicy::RANDOM,
              DeviceType::
                  CPU)  // (trait=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .reduce(
              [&](const auto &arg) -> std::vector<expression_t> {
                return {arg["cnt"]};
              },
              {SUM})
          .print(pg("pm-csv"));

  return rel.prepare();
}
