/*
    Proteus -- High-performance query processing on heterogeneous hardware.

                            Copyright (c) 2019
        Data Intensive Applications and Systems Laboratory (DIAS)
                École Polytechnique Fédérale de Lausanne

                            All Rights Reserved.

    Permission to use, copy, modify and distribute this software and
    its documentation is hereby granted, provided that both the
    copyright notice and this permission notice appear in all copies of
    the software, derivative works or modified versions, and any
    portions thereof, and that both notices appear in supporting
    documentation.

    This code is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. THE AUTHORS
    DISCLAIM ANY LIABILITY OF ANY KIND FOR ANY DAMAGES WHATSOEVER
    RESULTING FROM THE USE OF THIS SOFTWARE.
*/

// AUTOGENERATED FILE. DO NOT EDIT.

constexpr auto query = "ssb100_Q4_2";

#include "query.cpp.inc"

auto aff_parallel_cpu = []() -> std::unique_ptr<Affinitizer> {
  return std::make_unique<CpuNumaNodeAffinitizer>();
};

PreparedStatement Query::prepare42(bool memmv, size_t bloomSize) {
  auto rel57931 =
      getBuilder<Tplugin>()
          .scan<Tplugin>(
              "inputs/ssbm100/part.csv", {"p_partkey", "p_mfgr", "p_category"},
              getCatalog())  // (table=[[SSB, ssbm_part]], fields=[[0, 2, 3]],
          // traits=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .membrdcst(dop, true, true)
          .router(
              [&](const auto &arg) -> std::optional<expression_t> {
                return arg["__broadcastTarget"];
              },
              dop, 1, RoutingPolicy::HASH_BASED, dev,
              aff_parallel())  // (trait=[Pelago.[].packed.X86_64.homBrdcst.hetSingle])
          .to_gpu()  // (trait=[Pelago.[].packed.NVPTX.homBrdcst.hetSingle])
          .unpack()  // (trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle])
          .filter([&](const auto &arg) -> expression_t {
            return (eq(arg["p_mfgr"], "MFGR#1") | eq(arg["p_mfgr"], "MFGR#2"));
          })  // (condition=[OR(=($1, 'MFGR#1'), =($1, 'MFGR#2'))],
              // trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle],
              // isS=[false])
          .project([&](const auto &arg) -> std::vector<expression_t> {
            return {arg["p_partkey"], arg["p_category"]};
          })  // (p_partkey=[$0], p_category=[$2],
      // trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle])
      ;
  auto rel57935 =
      getBuilder<Tplugin>()
          .scan<Tplugin>(
              "inputs/ssbm100/date.csv", {"d_datekey", "d_year"},
              getCatalog())  // (table=[[SSB, ssbm_date]], fields=[[0, 4]],
                             // traits=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .membrdcst(dop, true, true)
          .router(
              [&](const auto &arg) -> std::optional<expression_t> {
                return arg["__broadcastTarget"];
              },
              dop, 1, RoutingPolicy::HASH_BASED, dev,
              aff_parallel())  // (trait=[Pelago.[].packed.X86_64.homBrdcst.hetSingle])
          .to_gpu()  // (trait=[Pelago.[].packed.NVPTX.homBrdcst.hetSingle])
          .unpack()  // (trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle])
          .filter([&](const auto &arg) -> expression_t {
            return (eq(arg["d_year"], 1997) | eq(arg["d_year"], 1998));
          })  // (condition=[OR(=($1, 1997), =($1, 1998))],
              // trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle],
              // isS=[false])
      ;
  auto rel57940 =
      getBuilder<Tplugin>()
          .scan<Tplugin>(
              "inputs/ssbm100/customer.csv", {"c_custkey", "c_region"},
              getCatalog())  // (table=[[SSB, ssbm_customer]], fields=[[0, 5]],
                             // traits=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .membrdcst(dop, true, true)
          .router(
              [&](const auto &arg) -> std::optional<expression_t> {
                return arg["__broadcastTarget"];
              },
              dop, 1, RoutingPolicy::HASH_BASED, dev,
              aff_parallel())  // (trait=[Pelago.[].packed.X86_64.homBrdcst.hetSingle])
          .to_gpu()  // (trait=[Pelago.[].packed.NVPTX.homBrdcst.hetSingle])
          .unpack()  // (trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle])
          .filter([&](const auto &arg) -> expression_t {
            return eq(arg["c_region"], "AMERICA");
          })  // (condition=[=($1, 'AMERICA')],
              // trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle],
              // isS=[false])
          .project([&](const auto &arg) -> std::vector<expression_t> {
            return {arg["c_custkey"]};
          })  // (c_custkey=[$0],
              // trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle])
      ;
  auto rel57945 =
      getBuilder<Tplugin>()
          .scan<Tplugin>(
              "inputs/ssbm100/supplier.csv",
              {"s_suppkey", "s_nation", "s_region"},
              getCatalog())  // (table=[[SSB, ssbm_supplier]], fields=[[0, 4,
                             // 5]],
                             // traits=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .membrdcst(dop, true, true)
          .router(
              [&](const auto &arg) -> std::optional<expression_t> {
                return arg["__broadcastTarget"];
              },
              dop, 128, RoutingPolicy::HASH_BASED, dev,
              aff_parallel())  // (trait=[Pelago.[].packed.X86_64.homBrdcst.hetSingle])
          .unpack()  // (trait=[Pelago.[].unpckd.NVPTX.homBrdcst.hetSingle])
          .filter([&](const auto &arg) -> expression_t {
            return eq(arg["s_region"], "AMERICA");
          })
          .bloomfilter_build(
              [&](const auto &arg) -> expression_t { return arg["s_suppkey"]; },
              bloomSize, 1)
          .project([&](const auto &arg) -> std::vector<expression_t> {
            return {arg["s_suppkey"], arg["s_nation"]};
          })
          .pack()
          .to_gpu()
          .unpack();

  auto rel =
      getBuilder<Tplugin>()
          .scan<Tplugin>(
              "inputs/ssbm100/lineorder.csv",
              {"lo_custkey", "lo_partkey", "lo_suppkey", "lo_orderdate",
               "lo_revenue", "lo_supplycost"},
              getCatalog())  // (table=[[SSB, ssbm_lineorder]], fields=[[2, 3,
                             // 4, 5, 12, 13]],
                             // traits=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .router(8, RoutingPolicy::LOCAL, DeviceType::CPU)
          .unpack()
          .bloomfilter_probe([&](const auto &arg) { return arg["lo_suppkey"]; },
                             bloomSize, 1)
          .pack()
          .router(8, RoutingPolicy::LOCAL, dev);

  if (memmv) rel = rel.memmove(8, dev);

  rel =
      rel.to_gpu()   // (trait=[Pelago.[].packed.NVPTX.homRandom.hetSingle])
          .unpack()  // (trait=[Pelago.[].unpckd.NVPTX.homRandom.hetSingle])
          .join(
              rel57940,
              [&](const auto &build_arg) -> expression_t {
                return build_arg["c_custkey"];
              },
              [&](const auto &probe_arg) -> expression_t {
                return probe_arg["lo_custkey"];
              },
              21,
              1048576)  // (condition=[=($1, $0)], joinType=[inner],
                        // rowcnt=[6.144E8], maxrow=[3000000.0],
                        // maxEst=[3000000.0], h_bits=[28],
                        // build=[RecordType(INTEGER c_custkey)],
                        // lcount=[1.2433094700931728E10],
                        // rcount=[6.1443906048E10], buildcountrow=[6.144E8],
                        // probecountrow=[6.1443906048E10])
          .join(
              rel57935,
              [&](const auto &build_arg) -> expression_t {
                return build_arg["d_datekey"];
              },
              [&](const auto &probe_arg) -> expression_t {
                return probe_arg["lo_orderdate"];
              },
              11,
              1024)  // (condition=[=($3, $0)], joinType=[inner],
                     // rowcnt=[785203.2], maxrow=[2556.0], maxEst=[2556.0],
                     // h_bits=[22], build=[RecordType(INTEGER d_datekey,
                     // INTEGER d_year)], lcount=[2.2404744691616405E7],
                     // rcount=[1.22887812096E10], buildcountrow=[785203.2],
                     // probecountrow=[1.22887812096E10])
          .join(
              rel57945,
              [&](const auto &build_arg) -> expression_t {
                return build_arg["s_suppkey"];
              },
              [&](const auto &probe_arg) -> expression_t {
                return probe_arg["lo_suppkey"];
              },
              17,
              65536)  // (condition=[=($4, $0)], joinType=[inner],
                      // rowcnt=[4.096E7], maxrow=[200000.0],
                      // maxEst=[200000.0], h_bits=[28],
                      // build=[RecordType(INTEGER s_suppkey, VARCHAR
                      // s_nation)], lcount=[1.4926851046814082E9],
                      // rcount=[3.0721953024E11], buildcountrow=[4.096E7],
                      // probecountrow=[3.0721953024E11])
          .join(
              rel57931,
              [&](const auto &build_arg) -> expression_t {
                return build_arg["p_partkey"];
              },
              [&](const auto &probe_arg) -> expression_t {
                return probe_arg["lo_partkey"];
              },
              21,
              1048576)  // (condition=[=($2, $0)], joinType=[inner],
                        // rowcnt=[5.7344E8], maxrow=[1400000.0],
                        // maxEst=[1400000.0], h_bits=[28],
                        // build=[RecordType(INTEGER p_partkey, VARCHAR
                        // p_category)], lcount=[2.3924273535728863E10],
                        // rcount=[3.68663436288E9], buildcountrow=[5.7344E8],
                        // probecountrow=[3.68663436288E9])
          .groupby(
              [&](const auto &arg) -> std::vector<expression_t> {
                return {arg["d_year"].as("PelagoAggregate#57958", "d_year"),
                        arg["s_nation"].as("PelagoAggregate#57958", "s_nation"),
                        arg["p_category"].as("PelagoAggregate#57958",
                                             "p_category")};
              },
              [&](const auto &arg) -> std::vector<GpuAggrMatExpr> {
                return {
                    GpuAggrMatExpr{(arg["lo_revenue"] - arg["lo_supplycost"])
                                       .as("PelagoAggregate#57958", "profit"),
                                   1, 0, SUM}};
              },
              10,
              131072)  // (group=[{0, 1, 2}], profit=[SUM($3)],
                       // trait=[Pelago.[].unpckd.NVPTX.homRandom.hetSingle])
          .pack()      // (trait=[Pelago.[].packed.NVPTX.homRandom.hetSingle],
                       // intrait=[Pelago.[].unpckd.NVPTX.homRandom.hetSingle],
          // inputRows=[1.4746537451520002E8], cost=[{225.8256 rows,
          // 225.60000000000002 cpu, 0.0 io}])
          .to_cpu()  // (trait=[Pelago.[].packed.X86_64.homRandom.hetSingle])
          .router(
              DegreeOfParallelism{1}, 128, RoutingPolicy::RANDOM,
              DeviceType::CPU,
              aff_reduce())  // (trait=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .memmove(8, DeviceType::CPU)
          .unpack()  // (trait=[Pelago.[].unpckd.NVPTX.homSingle.hetSingle])
          .groupby(
              [&](const auto &arg) -> std::vector<expression_t> {
                return {arg["d_year"].as("PelagoAggregate#57964", "d_year"),
                        arg["s_nation"].as("PelagoAggregate#57964", "s_nation"),
                        arg["p_category"].as("PelagoAggregate#57964",
                                             "p_category")};
              },
              [&](const auto &arg) -> std::vector<GpuAggrMatExpr> {
                return {GpuAggrMatExpr{
                    (arg["profit"]).as("PelagoAggregate#57964", "profit"), 1, 0,
                    SUM}};
              },
              10,
              131072)  // (group=[{0, 1, 2}], profit=[SUM($3)],
                       // trait=[Pelago.[].unpckd.NVPTX.homSingle.hetSingle])
          .sort(
              [&](const auto &arg) -> std::vector<expression_t> {
                return {arg["d_year"], arg["s_nation"], arg["p_category"],
                        arg["profit"]};
              },
              {direction::NONE, direction::ASC, direction::ASC,
               direction::ASC})  // (sort0=[$0], sort1=[$1], sort2=[$2],
                                 // dir0=[ASC], dir1=[ASC], dir2=[ASC],
                                 // trait=[Pelago.[0, 1,
                                 // 2].unpckd.X86_64.homSingle.hetSingle])
          .print(pg{"pm-csv"})   // (trait=[ENUMERABLE.[2, 3
      // DESC].unpckd.X86_64.homSingle.hetSingle])
      ;
  return rel.prepare();
}

PreparedStatement Query::prepare42_b(bool memmv, size_t bloomSize) {
  auto rel =
      getBuilder<Tplugin>()
          .scan<Tplugin>("inputs/ssbm100/lineorder.csv",
                         {"lo_custkey", "lo_partkey", "lo_suppkey",
                          "lo_orderdate", "lo_revenue", "lo_supplycost"},
                         getCatalog())  // (table=[[SSB, ssbm_lineorder]],
                                        // fields=[[2, 3, 4, 5, 12, 13]],
          // traits=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .router(
              DegreeOfParallelism{48}, 128, RoutingPolicy::LOCAL,
              DeviceType::CPU,
              aff_parallel_cpu())  // (trait=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .unpack()
          .bloomfilter_probe([&](const auto &arg) { return arg["lo_suppkey"]; },
                             bloomSize, 1)
          .reduce(
              [&](const auto &arg) -> std::vector<expression_t> {
                return {expression_t{1}.as("tmp", "cnt")};
              },
              {SUM})
          .router(
              DegreeOfParallelism{1}, 128, RoutingPolicy::RANDOM,
              DeviceType::CPU,
              aff_reduce())  // (trait=[Pelago.[].packed.X86_64.homSingle.hetSingle])
          .reduce(
              [&](const auto &arg) -> std::vector<expression_t> {
                return {arg["cnt"]};
              },
              {SUM})
          .print([&](const auto &arg) -> std::vector<expression_t> {
            return {arg["cnt"]};
          });

  return rel.prepare();
}
