set(RAPIDJSON_BUILD_DOC OFF CACHE BOOL "" FORCE)
set(RAPIDJSON_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(RAPIDJSON_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(RAPIDJSON_BUILD_CXX11 ON CACHE BOOL "" FORCE)
set(RAPIDJSON_HAS_CXX11_RVALUE_REFS ON CACHE BOOL "" FORCE)

set(GTEST_SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/googletest-download-src)

include(external/CMakeLists.txt.rapidjson.in)

find_package(RapidJSON CONFIG PATHS ${RapidJSON_BINARY_DIR} NO_DEFAULT_PATH)

add_library(RapidJSON::RapidJSON INTERFACE IMPORTED)

target_include_directories(RapidJSON::RapidJSON
	SYSTEM PUBLIC INTERFACE "${RapidJSON_INCLUDE_DIRS}"
)
